### ISSUE TITLE
Archive and/or Make the `www` repo private

### ISSUE THREAD

**Issue by mccurdyc** [gkapfham/www.gregorykapfhammer-old.com#14]
Is https://github.com/gkapfham/www still used? I was referring to it until I realized that this repo existed.

I checked the gitmodules and I didn't see references to `www`

If not, maybe archive it or make it private.

Thanks!

**Comment by gkapfham** [comment]
Hello @mccurdyc, thanks for raising this issue, I really appreciate it. Yes, it turns out that the repository that you were previously referencing is now deprecated and no longer in use. Following your suggestion, I have made it private. Going forward, this is the repository that I will now use for my web site. If I ultimately deprecate this repository, then I will make it private more rapidly than I did the last one!
